"""Apply length constraints to item table

Revision ID: 3585d1059e4a
Revises: c42fe35860e9
Create Date: 2026-01-03 11:33:18.316961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3585d1059e4a'
down_revision: Union[str, Sequence[str], None] = 'c42fe35860e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('item', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
